spring:
  application:
    name: order-module

logging:
  file:
    name: logs/app.log # ?? ?? ??
  level:
    root: info # ?? ?? ??
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # ?? ?? ??

